/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "name": string;
    }
    interface AppRoot {
    }
    interface PageHorse {
        "hid": string;
        "initialHorse": Horse;
    }
    interface PageHorses {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageHorseElement extends Components.PageHorse, HTMLStencilElement {
    }
    var HTMLPageHorseElement: {
        prototype: HTMLPageHorseElement;
        new (): HTMLPageHorseElement;
    };
    interface HTMLPageHorsesElement extends Components.PageHorses, HTMLStencilElement {
    }
    var HTMLPageHorsesElement: {
        prototype: HTMLPageHorsesElement;
        new (): HTMLPageHorsesElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "page-horse": HTMLPageHorseElement;
        "page-horses": HTMLPageHorsesElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "name"?: string;
    }
    interface AppRoot {
    }
    interface PageHorse {
        "hid"?: string;
        "initialHorse"?: Horse;
    }
    interface PageHorses {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "page-horse": PageHorse;
        "page-horses": PageHorses;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-horse": LocalJSX.PageHorse & JSXBase.HTMLAttributes<HTMLPageHorseElement>;
            "page-horses": LocalJSX.PageHorses & JSXBase.HTMLAttributes<HTMLPageHorsesElement>;
        }
    }
}
